name: Swift

on:
  push:
    branches: 
      - '**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: xcodebuild test -project Yumemi-ios-training.xcodeproj/ -scheme Yumemi-ios-training -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 8"

